import {StyleSheet} from 'react-native';

import {Theme} from '../../utils/types';

export const createStyles = (theme: Theme) =>
  StyleSheet.create({
    container: {
      padding: 16,
      paddingBottom: 32,
    },
    section: {
      marginBottom: 24,
    },
    sectionHeader: {
      fontWeight: 'bold',
      marginBottom: 4,
      color: theme.colors.onSurface,
    },
    sectionDescription: {
      marginBottom: 12,
      color: theme.colors.onSurfaceVariant,
    },
    installCard: {
      padding: 12,
      marginBottom: 12,
      borderRadius: 8,
      backgroundColor: theme.colors.surfaceContainerLow,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      overflow: 'hidden',
      position: 'relative',
    },
    installCardBody: {
      flex: 1,
      paddingRight: 12,
    },
    installCardTitle: {
      color: theme.colors.onSurface,
      fontWeight: '600',
    },
    installCardSubtitle: {
      color: theme.colors.onSurfaceVariant,
      marginTop: 2,
      fontSize: 12,
    },
    installCardProgressFill: {
      position: 'absolute',
      top: 0,
      left: 0,
      bottom: 0,
      backgroundColor: theme.colors.primaryContainer,
      opacity: 0.5,
    },
    installCardError: {
      backgroundColor: theme.colors.errorContainer,
    },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 12,
      paddingHorizontal: 4,
      minHeight: 44,
    },
    rowDisabled: {
      opacity: 0.45,
    },
    rowVoiceName: {
      flex: 1,
      color: theme.colors.onSurface,
    },
    rowVoiceNameSelected: {
      fontWeight: 'bold',
    },
    previewButton: {
      marginLeft: 8,
    },
    emptyText: {
      padding: 12,
      color: theme.colors.onSurfaceVariant,
      fontStyle: 'italic',
    },
    stepsRow: {
      marginTop: 12,
      paddingVertical: 8,
    },
    stepsLabel: {
      color: theme.colors.onSurfaceVariant,
      marginBottom: 6,
      fontSize: 12,
    },
    heroRow: {
      padding: 14,
      marginBottom: 14,
      borderRadius: 18,
      backgroundColor: theme.colors.surfaceContainerLow,
    },
    heroQualityBlock: {
      marginTop: 14,
      paddingHorizontal: 2,
    },
    heroQualityLabel: {
      color: theme.colors.onSurfaceVariant,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.8,
      textTransform: 'uppercase',
      marginBottom: 6,
    },
    voicesEmptyHint: {
      color: theme.colors.onSurfaceVariant,
      fontSize: 12.5,
      lineHeight: 18,
      marginBottom: 16,
      paddingHorizontal: 4,
    },
    voicesFooterLink: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 16,
      paddingHorizontal: 4,
      marginTop: 12,
      borderTopWidth: 1,
      borderTopColor: theme.colors.outlineVariant,
    },
    voicesFooterLinkLabel: {
      color: theme.colors.onSurface,
      fontSize: 14,
      fontWeight: '500',
    },
    engineGroup: {
      marginBottom: 16,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: theme.colors.outlineVariant,
      backgroundColor: theme.colors.surface,
      overflow: 'hidden',
    },
    engineGroupGradientFill: {
      borderRadius: 18,
    },
    engineGroupHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      paddingHorizontal: 14,
    },
    engineGroupHeaderText: {
      flex: 1,
      paddingHorizontal: 12,
    },
    engineGroupTitle: {
      color: theme.colors.onSurface,
      fontSize: 16,
      fontWeight: '700',
      letterSpacing: -0.2,
    },
    engineGroupSubtitle: {
      color: theme.colors.onSurfaceVariant,
      fontSize: 11,
      fontWeight: '600',
      letterSpacing: 0.4,
      marginTop: 2,
      textTransform: 'uppercase',
    },
    engineGroupDeleteBtn: {
      margin: 0,
    },
    engineGroupChevron: {
      width: 22,
      height: 22,
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: 4,
    },
    engineGroupChevronExpanded: {
      transform: [{rotate: '90deg'}],
    },
    engineGroupBody: {
      paddingHorizontal: 14,
      paddingBottom: 14,
      paddingTop: 4,
    },
    engineGroupCta: {
      borderRadius: 12,
    },
    engineGroupCtaLabel: {
      fontSize: 14,
      fontWeight: '700',
      letterSpacing: 0.1,
    },
    engineGroupProgressText: {
      color: theme.colors.onSurface,
      fontSize: 13,
      fontWeight: '600',
      fontVariant: ['tabular-nums'],
      letterSpacing: 0.2,
      paddingVertical: 8,
    },
    engineGroupErrorText: {
      color: theme.colors.error,
      fontSize: 12.5,
      lineHeight: 17,
      marginBottom: 10,
    },
    engineGroupEmpty: {
      color: theme.colors.onSurfaceVariant,
      fontSize: 12.5,
      fontStyle: 'italic',
      paddingVertical: 8,
    },
    heroRowBody: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    heroAvatarWrap: {
      marginRight: 14,
    },
    heroRowMain: {
      flex: 1,
      paddingRight: 12,
    },
    heroRowName: {
      color: theme.colors.onSurface,
      fontSize: 26,
      fontWeight: '700',
      letterSpacing: -0.3,
    },
    heroRowNameMuted: {
      color: theme.colors.onSurfaceVariant,
      fontSize: 22,
      fontWeight: '600',
    },
    heroSubtitle: {
      color: theme.colors.onSurfaceVariant,
      fontSize: 12,
      fontWeight: '600',
      marginTop: 4,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
    },
    heroPreviewButton: {
      margin: 0,
    },
    heroChipsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginTop: 6,
    },
    chip: {
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 10,
      marginRight: 6,
      marginTop: 4,
      backgroundColor: theme.colors.surfaceContainer,
    },
    chipText: {
      color: theme.colors.onSurfaceVariant,
      fontSize: 11,
      fontWeight: '600',
    },
    primaryRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 14,
      paddingHorizontal: 4,
      minHeight: 52,
    },
    primaryRowLabelBlock: {
      flex: 1,
      paddingRight: 12,
    },
    primaryRowLabel: {
      color: theme.colors.onSurface,
      fontSize: 16,
    },
    primaryRowDescription: {
      color: theme.colors.onSurfaceVariant,
      fontSize: 12,
      marginTop: 2,
    },
    primaryRowValue: {
      color: theme.colors.onSurfaceVariant,
      fontSize: 14,
      marginRight: 6,
    },
    groupHeader: {
      marginTop: 16,
      marginBottom: 4,
      paddingHorizontal: 4,
      color: theme.colors.onSurfaceVariant,
      fontSize: 12,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    voiceRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
      paddingHorizontal: 4,
      minHeight: 56,
    },
    voiceRowSelectedBar: {
      width: 3,
      alignSelf: 'stretch',
      borderRadius: 2,
      marginRight: 10,
    },
    voiceRowAvatarWrap: {
      marginRight: 12,
    },
    voiceRowLabelBlock: {
      flex: 1,
      paddingRight: 8,
    },
    voiceRowName: {
      color: theme.colors.onSurface,
      fontSize: 16,
      fontWeight: '500',
    },
    voiceRowNameSelected: {
      fontWeight: '700',
    },
    voiceRowSubline: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 2,
    },
    voiceRowEngineChipText: {
      color: theme.colors.onSurfaceVariant,
      fontSize: 11,
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginTop: 2,
    },
    voiceRowCheck: {
      marginLeft: 8,
      color: theme.colors.primary,
      fontWeight: '700',
    },
    inlineInstallCta: {
      marginTop: 4,
      marginBottom: 8,
      marginHorizontal: 4,
      padding: 12,
      borderRadius: 8,
      backgroundColor: theme.colors.surfaceContainerLow,
      overflow: 'hidden',
      position: 'relative',
    },
    inlineInstallCtaText: {
      color: theme.colors.onSurface,
      fontSize: 13,
      marginBottom: 8,
    },
    inlineInstallCtaActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
    },
    secondaryHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 4,
      paddingHorizontal: 4,
      marginBottom: 8,
    },
    secondaryHeaderTitle: {
      marginLeft: 4,
      color: theme.colors.onSurface,
      fontSize: 18,
      fontWeight: '700',
    },
    engineRowWrap: {
      marginBottom: 16,
    },
    engineRowHeader: {
      color: theme.colors.onSurface,
      fontWeight: '600',
      fontSize: 15,
      marginBottom: 2,
    },
    engineRowSubline: {
      color: theme.colors.onSurfaceVariant,
      fontSize: 12,
      marginBottom: 8,
    },
    deleteButton: {
      alignSelf: 'flex-start',
      marginTop: 4,
    },
    engineCardWrap: {
      marginBottom: 12,
    },
    engineCard: {
      borderRadius: 20,
      padding: 18,
      borderWidth: 1,
      borderColor: theme.colors.outlineVariant,
      backgroundColor: theme.colors.surface,
      overflow: 'hidden',
    },
    engineCardGradientFill: {
      borderRadius: 20,
    },
    engineCardHead: {
      flexDirection: 'row',
      alignItems: 'flex-start',
    },
    engineCardHeadText: {
      flex: 1,
      paddingLeft: 14,
      paddingRight: 8,
      paddingTop: 2,
    },
    engineCardStatusWrap: {
      alignItems: 'flex-end',
      flexShrink: 0,
      maxWidth: 96,
      paddingTop: 4,
    },
    engineCardTitle: {
      color: theme.colors.onSurface,
      fontSize: 19,
      fontWeight: '700',
      letterSpacing: -0.2,
    },
    engineCardTagline: {
      color: theme.colors.onSurfaceVariant,
      fontSize: 12.5,
      marginTop: 2,
      lineHeight: 17,
    },
    engineCardSpecs: {
      marginTop: 16,
      paddingVertical: 10,
      paddingHorizontal: 4,
      flexDirection: 'row',
      alignItems: 'stretch',
      borderRadius: 12,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.outlineVariant,
    },
    engineCardSpecCell: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 4,
    },
    engineCardSpecValue: {
      color: theme.colors.onSurface,
      fontSize: 16,
      fontWeight: '700',
      fontVariant: ['tabular-nums'],
      letterSpacing: -0.2,
    },
    engineCardSpecUnit: {
      color: theme.colors.onSurfaceVariant,
      fontSize: 9.5,
      fontWeight: '700',
      letterSpacing: 0.8,
      marginTop: 2,
    },
    engineCardSpecDivider: {
      width: 1,
      backgroundColor: theme.colors.outlineVariant,
      opacity: 0.6,
      marginVertical: 4,
    },
    engineCardActionRow: {
      marginTop: 14,
    },
    engineCardCta: {
      borderRadius: 12,
    },
    engineCardCtaLabel: {
      fontSize: 14,
      fontWeight: '700',
      letterSpacing: 0.1,
    },
    engineCardProgressBlock: {
      paddingVertical: 10,
      alignItems: 'center',
    },
    engineCardProgressText: {
      color: theme.colors.onSurface,
      fontSize: 13,
      fontWeight: '600',
      fontVariant: ['tabular-nums'],
      letterSpacing: 0.2,
    },
    engineCardReadyRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingLeft: 4,
    },
    engineCardReadyLabel: {
      color: theme.colors.onSurfaceVariant,
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 0.8,
      textTransform: 'uppercase',
    },
    engineCardErrorText: {
      color: theme.colors.error,
      fontSize: 12.5,
      marginTop: 14,
      lineHeight: 17,
    },
  });
